### ISSUE TITLE
needs a 'start' button or similar

### ISSUE THREAD

**Issue by pleabargain** [thibaudcolas/django-templates-live#1]
### Subject of the feature
After I edit the code there's no way to 'start' it again. Reffreshing the page deletes my edits.
Describe your issue here.
cannot edit and see results

### Problem
no start button
If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour
user should be able to edit the templates and then see changes in output
What should happen?  Please describe the desired behaviour.

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

**Comment by thibaudcolas** [comment]
👋 that’s exactly what the "Load Django" button does.
